server:
  port: 8080

spring:
  application:
    name: bus-analysis
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nettiexj.bus.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.nettiexj.bus.mapper: debug
